[project]
name = "mek2000"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Leonid-portal", email = "Leonsorvanov@outlook.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
]

[project.scripts]
mek2000 = "mek2000:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
